/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import tiendavideojuegos.TablaSociosModel;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import socios.Socio;
import utilidades.Utilidad;

/**
 *
 * @author link
 */
public class VentanaGestionSocios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionSocios
     */
    
    private String iConoFoto ="";
    TablaSociosModel tablaSociosModel = new TablaSociosModel();
    
    //private VentanaGestionSocios ventana=null;
    private VentanaPrincipal anterior=null;
    /*
    public static VentanaGestionSocios nuevaVentana(VentanaPrincipal padre){
        if(ventana == null){
            ventana = new VentanaGestionSocios();
            anterior = padre;
            System.out.println("Nueva instancia");
        }
        else{
            anterior = padre;
            System.out.println("Instancia creada");
        }
        return ventana;
    }
    */
    public VentanaGestionSocios(VentanaPrincipal anterior) {
        this.anterior = anterior;
        initComponents();
        prepararVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bFoto = new javax.swing.JButton();
        lNSocio = new javax.swing.JLabel();
        lNombreSocio = new javax.swing.JLabel();
        lCorreoSocio = new javax.swing.JLabel();
        lPasswordSocio = new javax.swing.JLabel();
        lTelefonoSocio = new javax.swing.JLabel();
        lFechaSocio = new javax.swing.JLabel();
        tNSocio = new javax.swing.JTextField();
        tNombreSocio = new javax.swing.JTextField();
        tCorreoSocio = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        tTelefono = new javax.swing.JTextField();
        bLimpiar = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        calendarFecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tBuscarNombre = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha Socio"));

        bFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFotoActionPerformed(evt);
            }
        });

        lNSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNSocio.setText("Nº Socio:");

        lNombreSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNombreSocio.setText("Nombre:");

        lCorreoSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lCorreoSocio.setText("E-Mail:");

        lPasswordSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lPasswordSocio.setText("Contraseña:");

        lTelefonoSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTelefonoSocio.setText("Teléfono:");

        lFechaSocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lFechaSocio.setText("Fecha de alta:");

        tNSocio.setEditable(false);
        tNSocio.setBackground(new java.awt.Color(230, 230, 230));

        tNombreSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreSocioKeyTyped(evt);
            }
        });

        tCorreoSocio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCorreoSocioFocusLost(evt);
            }
        });
        tCorreoSocio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tCorreoSocioPropertyChange(evt);
            }
        });

        tPassword.setText("jPasswordField1");
        tPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPasswordKeyTyped(evt);
            }
        });

        tTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tTelefonoFocusLost(evt);
            }
        });
        tTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tTelefonoKeyTyped(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.setToolTipText("Limpia los datos del formulario");
        bLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lNSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lCorreoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lPasswordSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(lTelefonoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lFechaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNombreSocio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tCorreoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(tNSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPassword))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(bLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEliminar)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNSocio)
                            .addComponent(tNSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNombreSocio)
                            .addComponent(tNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCorreoSocio)
                            .addComponent(tCorreoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPasswordSocio)
                            .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTelefonoSocio)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lFechaSocio))
                    .addComponent(calendarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLimpiar)
                    .addComponent(bSalvar)
                    .addComponent(bModificar)
                    .addComponent(bEliminar)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Socios"));

        jLabel1.setText("Buscar por Nombre:\n");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSociosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSocios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tBuscarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBuscar)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        // Para cerrar
        cerrarVentana();
    }//GEN-LAST:event_formWindowClosed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFotoActionPerformed
        // TODO add your handling code here:
        this.seleccionarFotoSocio();
    }//GEN-LAST:event_bFotoActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        cargarTablaSocios(this.tBuscarNombre.getText());
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tNombreSocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreSocioKeyTyped
        // TODO add your handling code here:
        activarBotonesNuevo();
    }//GEN-LAST:event_tNombreSocioKeyTyped

    private void tablaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSociosMouseClicked
        // TODO add your handling code here:
        int fila= this.tablaSocios.getSelectedRow();
        if(fila!=-1){
            cargarDdatosFormularioDeTabla(fila);
            // activamos boton eliminar
            this.bEliminar.setEnabled(true);
        } 
    }//GEN-LAST:event_tablaSociosMouseClicked

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        // TODO add your handling code here:
        salvarSocio();
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        modificarSocio();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        eliminarSocio();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void tCorreoSocioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tCorreoSocioPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tCorreoSocioPropertyChange

    private void tCorreoSocioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCorreoSocioFocusLost
        // TODO add your handling code here:
        validarCorreo();
    }//GEN-LAST:event_tCorreoSocioFocusLost

    private void tTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTelefonoFocusLost
        // TODO add your handling code here:
        validarTelefono();
    }//GEN-LAST:event_tTelefonoFocusLost

    private void tPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPasswordKeyTyped
        // TODO add your handling code here:
         activarBotonesNuevo();
    }//GEN-LAST:event_tPasswordKeyTyped

    private void tTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tTelefonoKeyTyped
        // TODO add your handling code here:
         activarBotonesNuevo();
    }//GEN-LAST:event_tTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
 

    private void prepararVentana() {
        this.setTitle("Gestión de Socios");
        this.anterior.setVisible(false);
        this.setVisible(true);
        this.ponerIconoVentana();
        this.setLocationRelativeTo(null); // Centramos
        ponerFotoSocio("socio.jpg");
        
        ponerIconos();
       
       // Todos os botones false
       this.bSalvar.setEnabled(false);
       this.bModificar.setEnabled(false);
       this.bEliminar.setEnabled(false);
       this.calendarFecha.setDate(new Date());
       
       
       
       // Cargamos alumnos
       cargarTablaSocios("");
    }
    
    private void ponerIconoVentana() {
        Utilidad c = Utilidad.nuevaInstancia();
        Toolkit t = Toolkit.getDefaultToolkit();
        this.setIconImage(t.getImage(c.getPatImagenes()+"icono.png"));
    }
    
    private void ponerFotoSocio(String foto) {
        Utilidad c = Utilidad.nuevaInstancia();
               
        //Ponemos el icono como imagen en el boton
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(c.getPathFotosSocios()+foto).getImage().getScaledInstance(95, 95, Image.SCALE_DEFAULT));
        this.bFoto.setIcon(imageIcon);
        this.iConoFoto = foto;
    }
    
    private void ponerIconos() {
        Utilidad c = Utilidad.nuevaInstancia();
        //Ponemos el icono como imagen label
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"limpiar.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        this.bLimpiar.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"salvar.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        this.bSalvar.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"modificar.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        this.bModificar.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"eliminar.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        this.bEliminar.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"buscar.png").getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        this.bBuscar.setIcon(imageIcon);

    }

    private void cerrarVentana() {
        anterior.setVisible(true);
    }
    
    
    
    private void limpiarCampos() {
        this.ponerFotoSocio("socio.jpg");
        this.tNSocio.setText("");
        this.tNombreSocio.setText("");
        this.tCorreoSocio.setText("");
        this.tPassword.setText("");
        this.tTelefono.setText("");
        this.calendarFecha.setDate(new Date());
        
       this.bSalvar.setEnabled(false);
       this.bModificar.setEnabled(false);
       this.bEliminar.setEnabled(false);
        
        
    }
    
    private void seleccionarFotoSocio() {
        //Seleccionamos la foto
        JFileChooser elegirRuta = new JFileChooser();
        elegirRuta.setDialogTitle("Selecciona el fichero de foto del alumno"); 
        FileNameExtensionFilter filtroFichero=new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        elegirRuta.setFileFilter(filtroFichero);
        int seleccion = elegirRuta.showOpenDialog(this);
        // Si pulsa guardar o aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = elegirRuta.getSelectedFile();
            System.out.println("fichero " + fichero.getAbsolutePath());
            Utilidad c = Utilidad.nuevaInstancia();
            c.copiarFotoSocio(fichero);
            ponerFotoSocio(fichero.getName());
            
        }
    }
    
    private void cargarTablaSocios(String filtro) {
        this.tablaSociosModel=new TablaSociosModel();
        
        tablaSocios.setRowSelectionAllowed(true);
        tablaSocios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        this.tablaSocios.setModel(tablaSociosModel);
        this.tablaSociosModel.setFila(Socio.listaSocios(filtro));
    }
    
    private void activarBotonesNuevo() {
        this.bSalvar.setEnabled(true);
        int fila= this.tablaSocios.getSelectedRow();
        if(fila>=0){
            this.bModificar.setEnabled(true);
            this.bEliminar.setEnabled(false);
        } 
        
    }
    
    private void cargarDdatosFormularioDeTabla(int fila) {
        this.tNSocio.setText(this.tablaSocios.getValueAt(fila, 0).toString());
        this.tNombreSocio.setText(this.tablaSocios.getValueAt(fila, 1).toString());
        this.tCorreoSocio.setText(this.tablaSocios.getValueAt(fila, 2).toString());
        //this.tPassword.setText(this.tablaSocios.getValueAt(fila, 3).toString());
        this.tTelefono.setText(this.tablaSocios.getValueAt(fila, 3).toString());
        this.calendarFecha.setDate(new Date(this.tablaSocios.getValueAt(fila, 4).toString()));
        this.ponerFotoSocio(this.tablaSocios.getValueAt(fila, 5).toString());
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bFoto;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalvar;
    private com.toedter.calendar.JDateChooser calendarFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCorreoSocio;
    private javax.swing.JLabel lFechaSocio;
    private javax.swing.JLabel lNSocio;
    private javax.swing.JLabel lNombreSocio;
    private javax.swing.JLabel lPasswordSocio;
    private javax.swing.JLabel lTelefonoSocio;
    private javax.swing.JTextField tBuscarNombre;
    private javax.swing.JTextField tCorreoSocio;
    private javax.swing.JTextField tNSocio;
    private javax.swing.JTextField tNombreSocio;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JTable tablaSocios;
    // End of variables declaration//GEN-END:variables

    private void salvarSocio() {
        boolean correcto = comprobarDatos();
        if(correcto){
            Socio s = new Socio();
            s.setNombre(this.tNombreSocio.getText());
            s.setCorreo(this.tCorreoSocio.getText());
            s.setPassword(this.tPassword.getText());
            s.setTelefono(this.tTelefono.getText());
            s.setFoto(this.iConoFoto);
            //Sacamos la fecha y su formato
            Date d = this.calendarFecha.getDate();
            String formato = this.calendarFecha.getDateFormatString();
            SimpleDateFormat sf = new SimpleDateFormat(formato);
            //System.err.println(String.valueOf(sf.format(d)));
            s.setFecha(sf.format(d));
            if(!s.existeBD()){
                s.insertarBD();
                JOptionPane.showMessageDialog(null, "Socio salvado correctamnete ","Salvado exitoso",JOptionPane.INFORMATION_MESSAGE);
                this.limpiarCampos();
                this.cargarTablaSocios("");
            }else{
              JOptionPane.showMessageDialog(null, "Ya existe un socio con este correo en el sistema","Error de salvado",JOptionPane.ERROR_MESSAGE);  
            }     
            
            
        }else{
             JOptionPane.showMessageDialog(null, "Error al salvar Socio","Error de salvado",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private boolean comprobarDatos() {
        if(this.tNombreSocio.getText().length()>0 && this.tCorreoSocio.getText().length()>0)
            return true;
        else
            return false;
    }

    private void modificarSocio() {
        boolean correcto = comprobarDatos();
        if(correcto){
            Socio s = new Socio();
            s.setCodigo(Integer.parseInt(this.tNSocio.getText()));
            s.setNombre(this.tNombreSocio.getText());
            s.setCorreo(this.tCorreoSocio.getText());
            s.setPassword(this.tPassword.getText());
            s.setTelefono(this.tTelefono.getText());
            s.setFoto(this.iConoFoto);
            //Sacamos la fecha y su formato
            Date d = this.calendarFecha.getDate();
            String formato = this.calendarFecha.getDateFormatString();
            SimpleDateFormat sf = new SimpleDateFormat(formato);
            //System.err.println(String.valueOf(sf.format(d)));
            s.setFecha(sf.format(d));
             //Preguntamos si queremos cerrar
            int seleccion = JOptionPane.showConfirmDialog(null, "¿Realmente desea modificar este socio/a?", "Salir", JOptionPane.YES_NO_OPTION);
            if (seleccion == JOptionPane.YES_OPTION){
                if(!s.existeBD()){
                    s.modificarBD();
                    JOptionPane.showMessageDialog(null, "Socio actualizado correctamnete ","Actualización exitosa",JOptionPane.INFORMATION_MESSAGE);
            
                    this.cargarTablaSocios("");
                    this.limpiarCampos();
                    this.bModificar.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Ya existe un socio con este correo en el sistema","Error de salvado",JOptionPane.ERROR_MESSAGE);  
                }    
            }
            
        }else{
             JOptionPane.showMessageDialog(null, "Error al actualizar Socio","Error de actualización",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminarSocio() {
            Socio s = new Socio();
            s.setCodigo(Integer.parseInt(this.tNSocio.getText()));
             //Preguntamos si queremos cerrar
            int seleccion = JOptionPane.showConfirmDialog(null, "¿Realmente desea modificar este socio?", "Salir", JOptionPane.YES_NO_OPTION);
            if (seleccion == JOptionPane.YES_OPTION){
                s.eliminarBD();
                JOptionPane.showMessageDialog(null, "Socio eliminado correctamnete ","Eliminación exitosa",JOptionPane.INFORMATION_MESSAGE);
           
                this.cargarTablaSocios("");
                this.limpiarCampos();
                this.bEliminar.setEnabled(false);
            }

    }

    private void validarCorreo() {
        String correo = this.tCorreoSocio.getText();
        Utilidad u = Utilidad.nuevaInstancia();
        if(!u.emailValido(correo)){
            JOptionPane.showMessageDialog(null, "La dirección de correo no es válida","Email erróneo",JOptionPane.ERROR_MESSAGE);
            this.tCorreoSocio.requestFocus();
        }
    }
    
    private void validarTelefono() {
        String correo = this.tTelefono.getText();
        Utilidad u = Utilidad.nuevaInstancia();
        if(!u.telefonoValido(correo)){
            JOptionPane.showMessageDialog(null, "El número de teléfono no es válido","Teléfono erróneo",JOptionPane.ERROR_MESSAGE);
            this.tTelefono.requestFocus();
        }
    }
    

}
