/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilidades.Utilidad;

/**
 *
 * @author link
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private static VentanaPrincipal ventana=null;
    
    public static VentanaPrincipal nuevaVentana(){
        if(ventana == null){
            ventana = new VentanaPrincipal();
            System.out.println("Nueva instancia");
        }
        else{
            System.out.println("Instancia creada");
        }
        return ventana;
    }
    
    private  VentanaPrincipal() {
        
        initComponents();
        prepararVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        bGestionSocios = new javax.swing.JButton();
        bInformes = new javax.swing.JButton();
        bGestionJuegos = new javax.swing.JButton();
        bCompras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lFoto = new javax.swing.JLabel();
        mMenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionJuegos = new javax.swing.JMenuItem();
        menuGestionSocios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCompras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuInformes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bGestionSocios.setText("Socios");
        bGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionSociosActionPerformed(evt);
            }
        });

        bInformes.setText("Informes");
        bInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInformesActionPerformed(evt);
            }
        });

        bGestionJuegos.setText("Juegos");
        bGestionJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestionJuegosActionPerformed(evt);
            }
        });

        bCompras.setText("Compras");
        bCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("IFP VIRGEN GAMES 1.0b");

        lFoto.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lFoto.setForeground(new java.awt.Color(204, 51, 0));
        lFoto.setMaximumSize(new java.awt.Dimension(95, 95));
        lFoto.setMinimumSize(new java.awt.Dimension(95, 95));
        lFoto.setSize(new java.awt.Dimension(95, 95));

        jMenu1.setText("Aplicación");

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        mMenuPrincipal.add(jMenu1);

        jMenu2.setText("Gestión");

        menuGestionJuegos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuGestionJuegos.setText("Gestión Juegos");
        menuGestionJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionJuegosActionPerformed(evt);
            }
        });
        jMenu2.add(menuGestionJuegos);

        menuGestionSocios.setText("Gestión de Socios");
        menuGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionSociosActionPerformed(evt);
            }
        });
        jMenu2.add(menuGestionSocios);

        mMenuPrincipal.add(jMenu2);

        jMenu3.setText("Compras");

        menuCompras.setText("Realizar Compra");
        menuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprasActionPerformed(evt);
            }
        });
        jMenu3.add(menuCompras);

        mMenuPrincipal.add(jMenu3);

        jMenu4.setText("Informes");

        menuInformes.setText("Ver Informes");
        menuInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformesActionPerformed(evt);
            }
        });
        jMenu4.add(menuInformes);

        mMenuPrincipal.add(jMenu4);

        jMenu5.setText("Ayuda");

        menuAcercaDe.setText("Acerca De");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        jMenu5.add(menuAcercaDe);

        mMenuPrincipal.add(jMenu5);

        setJMenuBar(mMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bGestionJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bInformes, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(bGestionSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGestionJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGestionSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionSociosActionPerformed
        this.mostrarGestionSocios();
    }//GEN-LAST:event_bGestionSociosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.cerrarAplicacion();
    }//GEN-LAST:event_formWindowClosing

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        this.cerrarAplicacion();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionSociosActionPerformed
        // TODO add your handling code here:
        this.mostrarGestionSocios();
    }//GEN-LAST:event_menuGestionSociosActionPerformed

    private void bGestionJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestionJuegosActionPerformed
        // TODO add your handling code here:
        this.mostrarGestionJuegos();
    }//GEN-LAST:event_bGestionJuegosActionPerformed

    private void menuGestionJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionJuegosActionPerformed
        // TODO add your handling code here:
        this.mostrarGestionJuegos();
    }//GEN-LAST:event_menuGestionJuegosActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        // TODO add your handling code here:
        VentanaAcercaDe v = new VentanaAcercaDe();
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void bComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprasActionPerformed
        // TODO add your handling code here:
        iniciarCompras();
    }//GEN-LAST:event_bComprasActionPerformed

    private void menuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprasActionPerformed
        // TODO add your handling code here:
        iniciarCompras();
    }//GEN-LAST:event_menuComprasActionPerformed

    private void bInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInformesActionPerformed
        // TODO add your handling code here:
        iniciarInformes();
    }//GEN-LAST:event_bInformesActionPerformed

    private void menuInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformesActionPerformed
        // TODO add your handling code here:
        iniciarInformes();
    }//GEN-LAST:event_menuInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    private void prepararVentana() {
        this.setTitle("Tienda de Videojuegos");
        this.setLocationRelativeTo(null);
        //tienda.setSize(600, 400);
        this.setResizable(false);
        this.ponerIconoVentana();
        this.setVisible(true);
        
        ponerIconos();
        
    }

    private void ponerIconos() {
        Utilidad c = Utilidad.nuevaInstancia();
        //Ponemos el icono como imagen label
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"icono.png").getImage().getScaledInstance(95, 95, Image.SCALE_DEFAULT));
        this.lFoto.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"juegos.png").getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        this.bGestionJuegos.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"socios.png").getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        this.bGestionSocios.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"compras.png").getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        this.bCompras.setIcon(imageIcon);
        
        imageIcon = new ImageIcon(new ImageIcon(c.getPatImagenes()+"informes.png").getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        this.bInformes.setIcon(imageIcon);
    }
    
     private void ponerIconoVentana() {
        Utilidad c = Utilidad.nuevaInstancia();
        Toolkit t = Toolkit.getDefaultToolkit();
        this.setIconImage(t.getImage(c.getPatImagenes()+"icono.png"));
    }
    
    private void mostrarGestionSocios(){
        //this.setVisible(false); // Me oculto
        VentanaGestionSocios ventana = new VentanaGestionSocios(this);
    }
    
    private void mostrarGestionJuegos(){
        //this.setVisible(false); // Me oculto
        VentanaGestionJuegos ventana = new VentanaGestionJuegos(this);
    }
    
    
    // Para cerrar la aplicación, pedimos confirmaciín
    private void cerrarAplicacion() {
        //Preguntamos si queremos cerrar
        int seleccion = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir de la aplicacion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (seleccion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCompras;
    private javax.swing.JButton bGestionJuegos;
    private javax.swing.JButton bGestionSocios;
    private javax.swing.JButton bInformes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JLabel lFoto;
    private javax.swing.JMenuBar mMenuPrincipal;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenuItem menuCompras;
    private javax.swing.JMenuItem menuGestionJuegos;
    private javax.swing.JMenuItem menuGestionSocios;
    private javax.swing.JMenuItem menuInformes;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables

    private void iniciarCompras() {
        VentanaSeleccionarSocio v = new VentanaSeleccionarSocio(this);
        
    }

    private void iniciarInformes() {
        VentanaInformes v = new VentanaInformes(this);
    }
}
